import type { Config } from 'tailwindcss';
import daisyui from 'daisyui';
import typography from '@tailwindcss/typography';
import { iconsPlugin, getIconCollections } from '@egoist/tailwindcss-icons';

export default {
  content: [
    './{pages,layouts,components,src}/**/*.{html,js,jsx,ts,tsx,vue}',
    'node_modules/daisyui/dist/**/*.js',
    'node_modules/react-daisyui/dist/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'b16-tm': {
          0: 'var(--color-b16-00)',
          1: 'var(--color-b16-01)',
          2: 'var(--color-b16-02)',
          3: 'var(--color-b16-03)',
          4: 'var(--color-b16-04)',
          5: 'var(--color-b16-05)',
          6: 'var(--color-b16-06)',
          7: 'var(--color-b16-07)',
          8: 'var(--color-b16-08)',
          9: 'var(--color-b16-09)',
          10: 'var(--color-b16-10)',
          11: 'var(--color-b16-11)',
          12: 'var(--color-b16-12)',
          13: 'var(--color-b16-13)',
          14: 'var(--color-b16-14)',
          15: 'var(--color-b16-15)',
        },
        'primary-tm': 'var(--color-primary)',
        'primary-content-tm': 'var(--color-primary-content)',
        'secondary-tm': 'var(--color-secondary)',
        'secondary-content-tm': 'var(--color-secondary-content)',
        'accent-tm': 'var(--color-accent)',
        'accent-content-tm': 'var(--color-accent-content)',
        'neutral-tm': 'var(--color-neutral)',
        'neutral-content-tm': 'var(--color-neutral-content)',
        'base-tm': {
          100: 'var(--color-base-100)',
          150: 'var(--color-base-150)',
          200: 'var(--color-base-200)',
          300: 'var(--color-base-300)',
        },
        'base-content-tm': 'var(--color-base-content)',
      },
      backgroundColor: {
        'highlight-color': 'var(--color-background-highlight)',
        'header-color':
          'color-mix(in srgb, var(--color-base-100) 30%, transparent)',
        'sidebar-color': 'var(--color-sidebar-background)',
      },
      borderColor: {
        'header-border-color':
          'color-mix(in srgb, var(--color-base-200) 50%, transparent)',
      },
    },
  },
  daisyui: {
    themes: [
      {
        onedark: {
          primary: '#98c379',
          secondary: '#61afef',
          accent: '#c678dd',
          neutral: '#abb2bf',
          'primary-content': '#282c34',
          'secondary-content': '#282c34',
          'accent-content': '#282c34',
          'neutral-content': '#282c34',
          'base-100': '#282c34',
          'base-150': '#353b45',
          'base-200': '#3e4451',
          'base-300': '#545862',
          'base-content': '#abb2bf',
        },
      },
      {
        onelight: {
          primary: '#50a14f',
          secondary: '#4078f2',
          accent: '#a626a4',
          neutral: '#3a3c43',
          'primary-content': '#fafafa',
          'secondary-content': '#fafafa',
          'accent-content': '#fafafa',
          'neutral-content': '#fafafa',
          'base-100': '#fafafa',
          'base-150': '#f0f0f1',
          'base-200': '#e5e5e6',
          'base-300': '#a0a1a7',
          'base-content': '#3a3c43',
        },
      },
      {
        monokai: {
          primary: '#f92672',
          secondary: '#a6e22e',
          accent: '#66d9ef',
          neutral: '#75715e',
          'primary-content': '#f8f8f2',
          'secondary-content': '#f8f8f2',
          'accent-content': '#f8f8f2',
          'neutral-content': '#f8f8f2',
          'base-100': '#272822',
          'base-150': '#383830',
          'base-200': '#49483e',
          'base-300': '#75715e',
          'base-content': '#f8f8f2',
        },
      },
      {
        solarized_dark: {
          primary: '#dc322f',
          secondary: '#859900',
          accent: '#268bd2',
          neutral: '#586e75',
          'primary-content': '#93a1a1',
          'secondary-content': '#93a1a1',
          'accent-content': '#93a1a1',
          'neutral-content': '#93a1a1',
          'base-100': '#002b36',
          'base-150': '#073642',
          'base-200': '#586e75',
          'base-300': '#657b83',
          'base-content': '#93a1a1',
        },
      },
      {
        solarized_light: {
          primary: '#dc322f',
          secondary: '#859900',
          accent: '#268bd2',
          neutral: '#93a1a1',
          'primary-content': '#586e75',
          'secondary-content': '#586e75',
          'accent-content': '#586e75',
          'neutral-content': '#586e75',
          'base-100': '#fdf6e3',
          'base-150': '#eee8d5',
          'base-200': '#93a1a1',
          'base-300': '#839496',
          'base-content': '#586e75',
        },
      },
      {
        darcula: {
          primary: '#0184bc',
          secondary: '#6a8759',
          accent: '#9876aa',
          neutral: '#323232',
          'primary-content': '#a9b7c6',
          'secondary-content': '#a9b7c6',
          'accent-content': '#a9b7c6',
          'neutral-content': '#a9b7c6',
          'base-100': '#2b2b2b',
          'base-150': '#323232',
          'base-200': '#323232',
          'base-300': '#606366',
          'base-content': '#a9b7c6',
        },
      },
      {
        tokyo_night_dark: {
          primary: '#9ece6a',
          secondary: '#0db9d7',
          accent: '#f7768e',
          'primary-content': '#a9b7d6',
          'secondary-content': '#a9b7d6',
          'accent-content': '#a9b7d6',
          'neutral-content': '#a9b7d6',
          'base-100': '#1a1b26',
          'base-150': '#16161e',
          'base-200': '#2f3549',
          'base-300': '#444b6a',
          'base-content': '#a9b7d6',
        },
      },
    ],
  },
  plugins: [
    daisyui,
    iconsPlugin({
      collections: getIconCollections([
        'carbon',
        'simple-icons',
        'icon-park-twotone',
        'icon-park-outline',
      ]),
    }),
    typography,
  ],
} satisfies Config;
